<a href="https://colab.research.google.com/github/ErickNoGit/Exerc-cios/blob/main/Atividade_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import pandas as pd

##Obtendo os dados: 
Ao rodarmos a célula abaixo vamos obter os dados diretamente do site:

http://dados.recife.pe.gov.br/tl/dataset/relacao-de-pessoas-vacinadas-covid-19/resource/966e9c4c-df45-40d7-9c58-2f13c61a6d28 


In [77]:
df1 = pd.read_csv('http://dados.recife.pe.gov.br/dataset/2b5ee58d-9535-4d80-ab32-f63fd475346e/resource/93f4e8c2-430f-4142-86b3-96dab4905b4e/download/casosgravescovid.csv', sep=";")

Utilize os comandos aprendidos em aula para os dados carregados, começando, preferencialmente, por:
- head()
- head(1-2)
- tail()
- info()
- describe()
- seguindo com outros aprendidos para manipulação de tratamento dos dados.

In [78]:
df1.describe()

data_notificacao      sexo   raca     etnia  idade  \
count             36435     36435  30106         4  36435   
unique              836         3      6         1    127   
top          2020-04-23  Feminino  Parda  Ignorado     57   
freq                464     18643  15040         4    646   

       municipio_residencia      bairro distrito_sanitario  \
count                 36435       36435              36435   
unique                    3         106                 10   
top                  Recife  BOA VIAGEM                 IV   
freq                  36433        2972               6392   

       data_inicio_sintomas                                   sintomas  \
count                 36435                                      34477   
unique                  850                                       3440   
top              2020-04-20  Febre, Tosse, Dispneia, Saturação O2 < 95   
freq                    359                                       2535   

       outros_sintomas            doencas_preexistentes  \
count             5974                            13698   
unique            2370                              244   
top            ASTENIA  Doenças Cardíacas ou Vasculares   
freq               946                             3827   

       outras_doencas_preexistentes  profissional_saude  \
count                           7807              27338   
unique                          3344                  2   
top                              HAS                NÃO   
freq                            1493              24424   

                        categoria_profissional classificacao_final  \
count                                     2914               36435   
unique                                      23                   4   
top     Outro profissional de serviço de saúde          CONFIRMADO   
freq                                      1900               17816   

          evolucao  data_obito  
count        35458        9344  
unique           5         785  
top     RECUPERADO  2020-05-09  
freq         18931          72

In [79]:
df2 = df1.copy()

**Listando colunas para definição do objetivo**

In [80]:
df2.columns.unique()

Index(['data_notificacao', 'sexo', 'raca', 'etnia', 'idade',
       'municipio_residencia', 'bairro', 'distrito_sanitario',
       'data_inicio_sintomas', 'sintomas', 'outros_sintomas',
       'doencas_preexistentes', 'outras_doencas_preexistentes ',
       'profissional_saude', 'categoria_profissional', 'classificacao_final',
       'evolucao', 'data_obito'],
      dtype='object')

#**Objetivo: Classificar uma porcentagem entre sexo feminino e masculino, apenas nos infectados!** 

In [81]:
#exclusão de colunas desnecessárias para esse objetivo
display(df1)

data_notificacao       sexo      raca etnia idade municipio_residencia  \
0           2020-05-30  Masculino    Branca   NaN    53               Recife   
1           2020-06-02   Feminino     Parda   NaN     0               Recife   
2           2020-06-02   Feminino     Parda   NaN    86               Recife   
3           2020-06-01  Masculino    Branca   NaN    66               Recife   
4           2020-06-02  Masculino     Preta   NaN    68               Recife   
...                ...        ...       ...   ...   ...                  ...   
36430       2022-06-08  Masculino  Ignorado   NaN    77               Recife   
36431       2022-06-09  Masculino     Parda   NaN    74               Recife   
36432       2022-06-10  Masculino     Parda   NaN    74               Recife   
36433       2022-06-12   Feminino   Amarela   NaN    73               Recife   
36434       2022-06-12   Feminino     Parda   NaN    66               Recife   

                     bairro distrito_sanitario data_inicio_sintomas  \
0                SAN MARTIN                  V           2020-05-25   
1      ALTO SANTA TEREZINHA                 II           2020-05-30   
2                ESPINHEIRO                III           2020-06-01   
3                CASA FORTE                III           2020-05-25   
4            ILHA DO RETIRO                 IV           2020-05-30   
...                     ...                ...                  ...   
36430    BREJO DA GUABIRABA                VII           2022-06-06   
36431       NOVA DESCOBERTA                VII           2022-06-06   
36432              BEBERIBE                 II           2022-06-03   
36433       ENGENHO DO MEIO                 IV           2022-06-11   
36434            BOA VIAGEM                 VI           2022-06-07   

                                                sintomas outros_sintomas  \
0      Febre, Tosse, Mialgia, Alteração/perda de olfa...             NaN   
1              Febre, Tosse, Dispneia, Saturação O2 < 95             NaN   
2                            Dispneia, Saturação O2 < 95             NaN   
3                                                    NaN             NaN   
4                     Tosse, Dispneia, Saturação O2 < 95             NaN   
...                                                  ...             ...   
36430                                           Dispneia             NaN   
36431  Tosse, Cansaço/fadiga, Desconforto respiratóri...             NaN   
36432                             Febre, Tosse, Dispneia             NaN   
36433  Dispneia, Desconforto respiratório / aperto to...             NaN   
36434  Tosse, Dispneia, Desconforto respiratório / ap...             RNC   

                           doencas_preexistentes  \
0                                            NaN   
1                                            NaN   
2                                            NaN   
3                                            NaN   
4                                            NaN   
...                                          ...   
36430                                        NaN   
36431                                        NaN   
36432                                   Diabetes   
36433  Doenças Cardíacas ou Vasculares, Diabetes   
36434                                        NaN   

      outras_doencas_preexistentes  profissional_saude categoria_profissional  \
0                               NaN                NaN                    NaN   
1                               NaN                NaN                    NaN   
2                               NaN                NaN                    NaN   
3                               NaN                NaN                    NaN   
4                               NaN                NaN                    NaN   
...                             ...                ...                    ...   
36430                           HAS                NÃO                    NaN   
36431 

In [82]:
df1.describe()

data_notificacao      sexo   raca     etnia  idade  \
count             36435     36435  30106         4  36435   
unique              836         3      6         1    127   
top          2020-04-23  Feminino  Parda  Ignorado     57   
freq                464     18643  15040         4    646   

       municipio_residencia      bairro distrito_sanitario  \
count                 36435       36435              36435   
unique                    3         106                 10   
top                  Recife  BOA VIAGEM                 IV   
freq                  36433        2972               6392   

       data_inicio_sintomas                                   sintomas  \
count                 36435                                      34477   
unique                  850                                       3440   
top              2020-04-20  Febre, Tosse, Dispneia, Saturação O2 < 95   
freq                    359                                       2535   

       outros_sintomas            doencas_preexistentes  \
count             5974                            13698   
unique            2370                              244   
top            ASTENIA  Doenças Cardíacas ou Vasculares   
freq               946                             3827   

       outras_doencas_preexistentes  profissional_saude  \
count                           7807              27338   
unique                          3344                  2   
top                              HAS                NÃO   
freq                            1493              24424   

                        categoria_profissional classificacao_final  \
count                                     2914               36435   
unique                                      23                   4   
top     Outro profissional de serviço de saúde          CONFIRMADO   
freq                                      1900               17816   

          evolucao  data_obito  
count        35458        9344  
unique           5         785  
top     RECUPERADO  2020-05-09  
freq         18931          72

In [83]:
df_list = df1[['sexo', 'idade', 'municipio_residencia', 'evolucao', 'data_obito']]
display(df_list)

sexo idade municipio_residencia                       evolucao  \
0      Masculino    53               Recife          ISOLAMENTO DOMICILIAR   
1       Feminino     0               Recife          ISOLAMENTO DOMICILIAR   
2       Feminino    86               Recife  INTERNADO LEITO DE ISOLAMENTO   
3      Masculino    66               Recife                     RECUPERADO   
4      Masculino    68               Recife  INTERNADO LEITO DE ISOLAMENTO   
...          ...   ...                  ...                            ...   
36430  Masculino    77               Recife                  INTERNADO UTI   
36431  Masculino    74               Recife  INTERNADO LEITO DE ISOLAMENTO   
36432  Masculino    74               Recife  INTERNADO LEITO DE ISOLAMENTO   
36433   Feminino    73               Recife                  INTERNADO UTI   
36434   Feminino    66               Recife                  INTERNADO UTI   

      data_obito  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
...          ...  
36430        NaN  
36431        NaN  
36432        NaN  
36433        NaN  
36434        NaN  

[36435 rows x 5 columns]

In [84]:
quantidade_M = df_list.loc[df_list['sexo'] == 'Masculino']
display(quantidade_M.describe())

sexo  idade municipio_residencia    evolucao  data_obito
count       17790  17790                17790       17307        4775
unique          1    121                    3           5         730
top     Masculino     58               Recife  RECUPERADO  2020-05-09
freq        17790    350                17788        9270          40

Segundo a tabela de valores acima, há uma quantidade de 17790 homens infectados, e desses 17790 morreram 4775. Com residência no Recife.

In [85]:
quantidade_F = df_list.loc[df_list['sexo'] == 'Feminino']
display(quantidade_F.describe())

sexo  idade municipio_residencia    evolucao  data_obito
count      18643  18643                18643       18149        4569
unique         1    127                    1           5         730
top     Feminino     60               Recife  RECUPERADO  2020-05-16
freq       18643    308                18643        9660          35

No sexo Feminino 18643 foram infectados, 4569 morreram e todos com residência em Recife.

In [86]:
feminino = 4569
masculino = 4775
total_mortes = masculino + feminino

In [87]:
df_list.value_counts('sexo')

sexo
Feminino     18643
Masculino    17790
Ignorado         2
dtype: int64

In [88]:
totalDeInfec = 18643 + 17790
print(totalDeInfec)

36433


**Segundo O IBGE,** com dados publicados pela globo:(https://g1.globo.com/pe/pernambuco/noticia/2020/08/27/pernambuco-atinge-96-milhoes-de-habitantes-em-2020-estima-ibge.ghtml), em 2020 havia **1.653.461 habitantes**. Desse número 36433 entre homens e mulheres de todas as idades estavam infectados com COVID-19.

In [89]:
#calculando porcentagem em relação a população
habitantes = 1653461
sexoMF = 36433
porcentagem = (sexoMF*100)/ habitantes
valor = str(("%.2f" %(porcentagem)))
valor += '%'
print('cerca de %s da população em Recife no ano de 2020!' %(valor))

cerca de 2.20% da população em Recife no ano de 2020!
